### ISSUE TITLE
King of Asia system

### ISSUE THREAD

**Issue by TeutonicThrash** [rickinator9/DK#16]
Purpose: To ensure that historically large empires are stable.

The mechanic will take the form of a unique (only one holder at a time) non-inheritable trait that can only be gained by fulfilling certain conditions:
•emperor tier
•not incapable
•controls: ◦c of sardis
◦d of phrygia
◦d of syria
◦d of babylon

Effects:
•vassal opinion +40
•general opinion +10

The trait will be assigned to all historical "Kings of Asia" (Achaemenids, Argeads, etc).

**Comment by rickinator9** [comment]
I consider this complete as of b274b2a
